[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyplants"
version = "0.0.1"
description = "A collection of phenological and disease models for plants"
readme = "README.md"
requires-python = ">= 3.8"

[project.optional-dependencies]
docs = ["sphinx"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]