[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyplants"
version = "0.1.1"
description = "A collection of phenological and disease models for plants"
authors = [
	{ name="iXemLabs", email="giovanni.colucci@polito.it" }
]
requires-python = ">= 3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research"
]
readme = "README.md"
license = {text = "Apache-2.0"}

[project.optional-dependencies]
docs = ["sphinx"]

[project.urls]
Homepage = "https://github.com/iXemLabs/pyplants"
Issues = "https://github.com/iXemLabs/pyplants/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]